# Required
version: 2

# OS and Tools
build:
  os: windows
  tools:
    python: "3.10"

sphinx:
  configuration: statesxt/docs/conf.py

python:
  install:
    - requirements: statesxt/docs/requirements.txt